#!/bin/bash

[[ $# -lt 1 ]] && echo "Need a subcommand." && exit 1

source ${PKG_PATH}/.env
dc_file=${PKG_PATH}/.docker/docker-compose.yml

fn_login()
{
    echo ${CR_PAT} | docker login ghcr.io -u ${CR_USER} --password-stdin
}

case $1 in
    "build")
        fn_login
        docker buildx bake -f ${dc_file} --load litestar
        ;;
    "push")
        fn_login
        docker push ${DOCKER_REGISTRY}/test-litestar:${GIT_REF}
        docker push ${DOCKER_REGISTRY}/test-litestar:latest
        ;;
    "up")
        docker compose -f ${dc_file} up -d
        ;;
    "down")
        docker compose -f ${dc_file} down --remove-orphans
        ;;
    "bash")
        docker compose -f ${dc_file} run -it litestar bash
        ;;
    *)
        docker compose -f ${dc_file} $1 litestar ${@:2}
esac
